version: "3.8"


services:
  container_name: mysql
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: BankDB
    networks:
      - bankapp
    volumes:
       - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
  
 bankapp:
   container_name: bankapp
   image: sakshamkamble/springboot-bankapp:latest
   ports:
     - 8080:8080 
   environment: 
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
     SPRING_DATASOURCE_PASSWORD: Test@123
   networks:
     - bankapp
    depends_on:
      - mysql
          
